TABULATOR_COLUMNS = [
    {"title": "Client", "field": "client_name", "headerFilter": True},
    {"title": "Client ID", "field": "client_id"},
    {"title": "Account", "field": "account_name", "headerFilter": True},
    {"title": "Account ID", "field": "account_id"},
    {"title": "Instrument", "field": "instrument_name", "headerFilter": True},
    {"title": "Symbol", "field": "symbol"},
    {"title": "Units", "field": "units"},
    {"title": "Market Price", "field": "market_price", "formatter": "money"},
    {"title": "Market Value", "field": "market_value", "formatter": "money"},
    {"title": "Book Value", "field": "book_value", "formatter": "money"},
    {"title": "Deposits", "field": "deposits", "formatter": "money"},
    {"title": "Withdrawals", "field": "withdrawals", "formatter": "money"},
    {"title": "Net Deposits", "field": "net_deposits", "formatter": "money"},
    {"title": "Total Return", "field": "total_return", "formatter": "percent"},
    {
        "title": "Cumulative Return",
        "field": "cumulative_return",
        "formatter": "percent",
    },
    {"title": "% of Portfolio", "field": "pct_of_portfolio", "formatter": "percent"},
]

GRID_FIELDS = [
    {"id": "client_name", "name": "Client"},
    {"id": "client_id", "name": "Client ID"},
    {"id": "account_name", "name": "Account"},
    {"id": "account_id", "name": "Account ID"},
    {"id": "instrument_name", "name": "Instrument"},
    {"id": "symbol", "name": "Symbol"},
    {"id": "units", "name": "Units"},
    {"id": "market_price", "name": "Market Price", "formatter": "currency"},
    {"id": "market_value", "name": "Market Value", "formatter": "currency"},
    {"id": "book_value", "name": "Book Value", "formatter": "currency"},
    {"id": "deposits", "name": "Deposits", "formatter": "currency"},
    {"id": "withdrawals", "name": "Withdrawals", "formatter": "currency"},
    {"id": "net_deposits", "name": "Net Deposits", "formatter": "currency-colored"},
    {"id": "total_return", "name": "Total Return", "formatter": "percent-colored"},
    {"id": "cumulative_return", "name": "Cumulative Return", "formatter": "percent"},
    {"id": "pct_of_portfolio", "name": "% of Portfolio", "formatter": "percent"},
]


TEST_DATA = {
    "date": "2025-05-10",
    "client_id": "C001",
    "client_name": "Alan Guerrero",
    "account_id": "ACCT-C001-1",
    "account_name": "Black Margin Account",
    "symbol": "EUR",
    "instrument_name": "EUR Cash",
    "units": 52686.84,
    "market_price": 1.0,
    "market_value": 52686.84,
    "book_value": 52994.0,
    "deposits": 31734.63,
    "withdrawals": 24301.01,
    "net_deposits": 7433.62,
    "total_return": 0.0457,
    "cumulative_return": 0.2043,
    "pct_of_portfolio": 0.0707,
}
