# Generated by Django 5.1.6 on 2025-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScriptExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("script_name", models.CharField(max_length=255)),
                ("arguments", models.TextField(blank=True, null=True)),
                ("output", models.TextField(blank=True, null=True)),
                ("success", models.BooleanField(default=False)),
                ("duration", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
