# Generated by Django 5.2.1 on 2025-06-06 16:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioDataSet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("logs", models.TextField(blank=True)),
                (
                    "column_names",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Cached list of variable names (columns) extracted from the file",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_datasets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestep", models.IntegerField()),
                ("variable", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="scenario_analysis.scenariodataset",
                    ),
                ),
            ],
            options={
                "ordering": ["timestep"],
            },
        ),
        migrations.AddConstraint(
            model_name="scenariodataset",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_scenario_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="scenariovalue",
            index=models.Index(
                fields=["dataset", "variable", "timestep"],
                name="scenario_an_dataset_c37ec4_idx",
            ),
        ),
    ]
