# Generated by Django 5.2.1 on 2025-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenario_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariodataset",
            name="filename",
            field=models.FileField(upload_to="scenario_analysis/scenarios/"),
        ),
    ]
