# Generated by Django 5.2.1 on 2025-06-09 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario_analysis", "0002_alter_scenariodataset_filename"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scenariodataset",
            old_name="filename",
            new_name="file",
        ),
    ]
