# Generated by Django 5.2 on 2025-04-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("open_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="dashboard_h_date_7a7380_idx")
                ],
                "unique_together": {("date",)},
            },
        ),
    ]
