# Generated by Django 5.2 on 2025-04-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="historicalprice",
            name="dashboard_h_date_7a7380_idx",
        ),
        migrations.AlterUniqueTogether(
            name="historicalprice",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="historicalprice",
            constraint=models.UniqueConstraint(fields=("date",), name="unique_date"),
        ),
    ]
