# Generated by Django 5.2.1 on 2025-05-10 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_remove_historicalprice_dashboard_h_date_7a7380_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=30)),
                ("account_name", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="dashboard.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("units", models.DecimalField(decimal_places=2, max_digits=20)),
                ("market_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("market_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("book_value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("deposits", models.DecimalField(decimal_places=2, max_digits=20)),
                ("withdrawals", models.DecimalField(decimal_places=2, max_digits=20)),
                ("net_deposits", models.DecimalField(decimal_places=2, max_digits=20)),
                ("total_return", models.DecimalField(decimal_places=4, max_digits=8)),
                (
                    "cumulative_return",
                    models.DecimalField(decimal_places=4, max_digits=8),
                ),
                (
                    "pct_of_portfolio",
                    models.DecimalField(decimal_places=4, max_digits=6),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="dashboard.account",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="dashboard.instrument",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "account", "instrument")},
            },
        ),
    ]
