# Generated by Django 5.1 on 2025-03-13 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("exchange", models.CharField(blank=True, max_length=50, null=True)),
                ("sector", models.CharField(blank=True, max_length=50, null=True)),
                ("industry", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TickerMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("long_business_summary", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                ("beta", models.FloatField(blank=True, null=True)),
                ("dividend_yield", models.FloatField(blank=True, null=True)),
                ("full_time_employees", models.IntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "ticker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="dashboard.ticker",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("high_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("low_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("close_price", models.DecimalField(decimal_places=4, max_digits=12)),
                ("volume", models.BigIntegerField()),
                (
                    "ticker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_prices",
                        to="dashboard.ticker",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
