# Generated by Django 5.2.1 on 2025-05-24 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modelling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDACurveRunMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_balance", models.FloatField()),
                ("WAL", models.FloatField()),
                ("coupon_rate", models.FloatField()),
                ("face_value", models.FloatField()),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="modelling.sdacurveinputs",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SDACurveCashFlows",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestep", models.IntegerField()),
                ("balance", models.FloatField()),
                ("interest", models.FloatField()),
                ("default", models.FloatField()),
                ("prepayment", models.FloatField()),
                ("principal", models.FloatField()),
                ("totalcf", models.FloatField()),
                (
                    "run_metrics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflows",
                        to="modelling.sdacurverunmetrics",
                    ),
                ),
            ],
        ),
    ]
